### ISSUE TITLE
Profession level

### ISSUE THREAD

**Issue by Lihvar** [insunaa/cmangos_importer#5]
Profession levels are set to maximum amount instead of accurate values

![image](https://user-images.githubusercontent.com/33036901/223571730-2eb41254-8130-4da7-91cf-e226731c460b.png)

![image](https://user-images.githubusercontent.com/33036901/223571775-f4997bc3-8f59-4890-9851-5ed877313fa7.png)

**Comment by insunaa** [comment]
I can probably retrieve the skills with this, no promises
https://warcraft.wiki.gg/wiki/API_GetSkillLineInfo
